export const contactFaqs = [
  {
    question: "How fast can you deliver a quote?",
    answer:
      "We aim to share quotes within 4 to 8 business hours for standard jobs. Send your DXF, DWG, STEP, IGES, or PDF drawings with material details for the fastest response.",
  },
  {
    question: "What file formats do you accept?",
    answer:
      "We accept DXF, DWG, STEP, IGES, PDF drawings, and hand-marked sketches. Our team reviews every submission for manufacturability before production.",
  },
  {
    question: "What is your minimum order quantity?",
    answer:
      "We support everything from one-off prototypes to repeat production batches, depending on the process, material, and delivery schedule.",
  },
  {
    question: "Do you offer on-site pickup?",
    answer:
      "Yes. You can arrange pickup from our Kamrej, Surat, Gujarat facility, and we can also coordinate dispatch across India.",
  },
] as const;

export const siteConfig = {
  name: "Balaji Engineering Works",
  legalName: "Balaji Engineering Works",
  shortName: "Balaji Engineering",
  alternateName: "Sheet Metal Bending Works",
  url:
    process.env.NEXT_PUBLIC_SITE_URL || "https://www.cncplatebending.com",
  ogImage: "/opengraph.jpg",
  description:
    "Balaji Engineering Works is a Surat-based manufacturer and service provider for CNC laser cutting services in Surat, CNC plasma cutting services in Surat, CNC plate bending service in Surat, sheet metal fabrication, and industrial products including base plates, foundation bolts, purlins, perforated sheets, and heavy fabrication.",
  phone: "+919978753398",
  phoneDisplay: "+91 84888 01197",
  email: "mayankpokiya3@gmail.com",
  foundingDate: "2001",
  priceRange: "$$",
  gstNumber: "24BCUPS8314Q1ZK",
  businessType: "Manufacturer and Service Provider",
  locale: "en_IN",
  language: "en-IN",
  indiaMartProfile: "https://www.balajiengineeringworks.in/",
  serviceAreas: [
    "Surat",
    "Kamrej",
    "Bharuch",
    "Ankleshwar",
    "Vapi",
    "Vadodara",
    "Ahmedabad",
    "Gujarat",
    "Maharashtra",
    "Mumbai",
    "Rajasthan",
    "Madhya Pradesh",
    "India",
  ],
  industries: [
    "Sheet Metal Fabrication",
    "Sheet Metal Forming",
    "Sheet Metal Forming Industries Surat",
    "Structural Steel Fabrication",
    "CNC Laser Cutting",
    "CNC Plasma Cutting",
    "Steel Shearing",
    "Steel Plate Bending",
    "Press Brake Bending",
    "Plate Rolling",
    "Profile Cutting",
    "Steel Punching",
    "Heavy Fabrication",
    "Industrial Manufacturing",
    "Industrial Product Manufacturing",
    "Structural Steel Components",
  ],
  keywords: [
    // === BRAND ===
    "Balaji Engineering Works",
    "Balaji Engineering Works Surat",
    "balaji engineering surat",
    "balaji engineering gujarat",
    "balaji sheet metal works",
    // === CNC PLATE BENDING — PRIMARY FOCUS ===
    "CNC plate bending",
    "CNC plate bending service",
    "CNC plate bending surat",
    "CNC plate bending gujarat",
    "CNC plate bending india",
    "CNC plate bending near me",
    "CNC plate bending company",
    "CNC plate bending manufacturer",
    "CNC plate bending supplier",
    "CNC plate bending price",
    "CNC plate bending rate",
    "CNC plate bending cost",
    "CNC plate bending quote",
    "CNC plate bending job work",
    "cnc plate bending service surat",
    "CNC press brake bending",
    "CNC press brake bending surat",
    "CNC press brake service",
    "CNC press brake surat",
    "CNC press brake india",
    "CNC press brake near me",
    "press brake bending",
    "press brake bending service",
    "press brake bending surat",
    "press brake bending gujarat",
    "press brake bending india",
    "press brake bending near me",
    "press brake bending company",
    "press brake bending manufacturer",
    "press brake service",
    "press brake job work",
    "press brake bending price",
    "press brake bending rate",
    "press brake bending cost",
    "press brake bending quote",
    "hydraulic press brake service",
    "heavy duty press brake bending",
    "precision press brake bending",
    "V bending service",
    "U bending service",
    "Z bending service",
    "box bending service",
    "complex shape bending",
    "multi-bend fabrication",
    // === CNC BENDING ===
    "CNC bending service",
    "CNC bending surat",
    "CNC bending gujarat",
    "CNC bending india",
    "CNC bending near me",
    "CNC bending company",
    "CNC bending price",
    "CNC bending rate",
    "CNC bending job work",
    "CNC bending manufacturer",
    // === PLATE BENDING ===
    "plate bending service",
    "plate bending works",
    "plate bending surat",
    "plate bending gujarat",
    "plate bending india",
    "plate bending near me",
    "plate bending company",
    "plate bending manufacturer",
    "plate bending supplier",
    "plate bending job work",
    "plate bending price",
    "plate bending rate",
    "plate bending quote",
    "heavy plate bending",
    "thick plate bending",
    "thin sheet bending",
    "industrial plate bending",
    // === SHEET METAL BENDING ===
    "sheet metal bending",
    "sheet metal bending service",
    "sheet metal bending surat",
    "sheet metal bending gujarat",
    "sheet metal bending india",
    "sheet metal bending near me",
    "sheet metal bending company",
    "sheet metal bending price",
    "sheet metal bending rate",
    "sheet metal bending job work",
    "sheet bending service",
    "metal bending service",
    "steel bending service",
    "metal bending works",
    "channel bending service",
    "angle bending service",
    "flat bar bending",
    // === CNC LASER CUTTING ===
    "CNC laser cutting",
    "CNC laser cutting service",
    "CNC laser cutting surat",
    "CNC laser cutting gujarat",
    "CNC laser cutting india",
    "CNC laser cutting near me",
    "CNC laser cutting company",
    "CNC laser cutting price",
    "CNC laser cutting rate",
    "CNC laser cutting rate per kg",
    "CNC laser cutting job work",
    "laser cutting service",
    "laser cutting works",
    "laser cutting surat",
    "laser cutting gujarat",
    "laser cutting india",
    "laser cutting near me",
    "laser cutting company",
    "laser cutting price",
    "laser cutting price per kg",
    "laser cutting cost",
    "laser cutting rate",
    "laser cutting job work",
    "fiber laser cutting",
    "fiber laser cutting surat",
    "fiber laser cutting india",
    "2D laser cutting",
    "DXF laser cutting",
    "DXF file CNC bending service",
    "custom laser cutting",
    "precision laser cutting",
    "MS laser cutting",
    "SS laser cutting",
    "aluminum laser cutting",
    // === CNC PLASMA CUTTING ===
    "CNC plasma cutting",
    "CNC plasma cutting service",
    "CNC plasma cutting surat",
    "CNC plasma cutting gujarat",
    "CNC plasma cutting india",
    "CNC plasma cutting near me",
    "CNC plasma cutting price",
    "CNC plasma cutting rate",
    "CNC plasma cutting job work",
    "plasma cutting service",
    "plasma cutting surat",
    "plasma cutting india",
    "plasma cutting price",
    "plasma cutting rate",
    "plasma cutting job work",
    "heavy plate plasma cutting",
    "MS plasma cutting",
    // === PLATE ROLLING ===
    "plate rolling service",
    "plate rolling surat",
    "plate rolling gujarat",
    "plate rolling india",
    "plate rolling company",
    "plate rolling price",
    "plate rolling job work",
    "cylinder rolling service",
    "cone rolling service",
    "pipe rolling service",
    "pipe rolling surat",
    "shell rolling service",
    "tank shell rolling",
    "pressure vessel rolling",
    "plate rolling and bending",
    // === PROFILE CUTTING ===
    "profile cutting service",
    "profile cutting surat",
    "CNC profile cutting",
    "steel profile cutting",
    "plasma profile cutting",
    "laser profile cutting",
    "flat bar cutting service",
    "angle cutting service",
    "channel cutting service",
    // === SHEET METAL FABRICATION ===
    "sheet metal fabrication",
    "sheet metal fabrication service",
    "sheet metal fabrication surat",
    "sheet metal fabrication gujarat",
    "sheet metal fabrication india",
    "sheet metal fabrication near me",
    "sheet metal fabrication company",
    "sheet metal fabrication manufacturer",
    "sheet metal fabrication supplier",
    "sheet metal fabrication price",
    "sheet metal fabrication cost",
    "sheet metal fabrication job work",
    "custom sheet metal fabrication",
    "precision sheet metal fabrication",
    "heavy sheet metal fabrication",
    "heavy fabrication surat",
    "heavy fabrication india",
    "industrial sheet metal fabrication",
    "structural sheet metal fabrication",
    "sheet metal parts manufacturer",
    "sheet metal components manufacturer",
    "sheet metal parts supplier",
    "contract sheet metal fabrication",
    "outsource sheet metal fabrication",
    "B2B sheet metal fabrication",
    "bulk sheet metal fabrication",
    "prototype sheet metal fabrication",
    "DWG file metal fabrication",
    "STEP file fabrication",
    // === MATERIALS ===
    "MS plate bending surat",
    "mild steel plate bending service",
    "mild steel fabrication surat",
    "MS sheet cutting",
    "MS plate cutting",
    "MS fabrication surat",
    "mild steel laser cutting",
    "stainless steel fabrication",
    "stainless steel sheet cutting",
    "stainless steel laser cutting",
    "stainless steel bending",
    "SS 304 fabrication",
    "SS 316 fabrication",
    "SS plate bending surat",
    "SS sheet cutting surat",
    "CRCA sheet bending",
    "CRCA sheet cutting",
    "CRCA sheet fabrication",
    "HR plate bending surat",
    "HR sheet fabrication",
    "hot rolled steel fabrication",
    "cold rolled steel fabrication",
    "galvanized sheet fabrication",
    "GI sheet fabrication surat",
    "GI sheet cutting",
    "galvanized sheet bending surat",
    "aluminum sheet bending surat",
    "aluminum sheet fabrication",
    "aluminium fabrication surat",
    "carbon steel fabrication",
    "structural steel fabrication",
    "high tensile steel fabrication",
    "pressure vessel steel fabrication",
    // === PRODUCTS — BASE PLATES ===
    "base plate manufacturer",
    "MS base plate manufacturer",
    "base plate manufacturer surat",
    "base plate manufacturer gujarat",
    "base plate manufacturer india",
    "MS base plate supplier",
    "base plate supplier surat",
    "custom base plate fabrication",
    "column base plate manufacturer",
    "structural base plate manufacturer",
    "base plates for steel structures",
    "base plate wholesale surat",
    "base plate bulk order india",
    // === PRODUCTS — FOUNDATION BOLTS ===
    "foundation bolt manufacturer",
    "foundation bolt manufacturer surat",
    "foundation bolt manufacturer gujarat",
    "foundation bolt manufacturer india",
    "foundation bolt supplier surat",
    "foundation bolts wholesale",
    "MS foundation bolt manufacturer",
    "anchor bolt manufacturer surat",
    "anchor bolt supplier",
    "J type foundation bolt",
    "L type foundation bolt",
    "bent anchor bolt manufacturer",
    "custom foundation bolt",
    "foundation bolt price surat",
    "foundation bolt bulk order",
    "heavy duty anchor bolt",
    "M20 foundation bolt",
    "M24 foundation bolt",
    "M30 foundation bolt",
    "M36 foundation bolt",
    // === PRODUCTS — PURLINS ===
    "purlin manufacturer surat",
    "purlin manufacturer gujarat",
    "purlin manufacturer india",
    "purlin supplier surat",
    "c purlin manufacturer surat",
    "z purlin manufacturer surat",
    "c and z purlin manufacturer surat",
    "steel purlin manufacturer",
    "MS purlin manufacturer",
    "roofing purlin manufacturer",
    "structural purlin manufacturer",
    "purlin for warehouse",
    "purlin for factory",
    "purlin for industrial building",
    "purlin price surat",
    "purlin wholesale india",
    "cold formed purlin",
    // === PRODUCTS — PERFORATED SHEETS ===
    "perforated sheet manufacturer surat",
    "perforated sheet manufacturer gujarat",
    "perforated sheet manufacturer india",
    "perforated sheet supplier surat",
    "MS perforated sheet manufacturer",
    "SS perforated sheet manufacturer",
    "custom perforated sheet",
    "perforated sheet price surat",
    "perforated sheet wholesale",
    "ventilation perforated sheet",
    // === PRODUCTS — DECKING & ROOFING ===
    "decking sheet supplier surat",
    "decking sheet manufacturer surat",
    "floor decking sheet",
    "metal decking supplier",
    "corrugated sheet manufacturer surat",
    "corrugated roofing sheet surat",
    "corrugated metal sheet supplier",
    "GI corrugated sheet",
    "roofing sheet supplier surat",
    "industrial roofing sheet surat",
    // === PRODUCTS — STEEL PALLETS ===
    "steel pallet manufacturer surat",
    "steel pallet manufacturer gujarat",
    "MS pallet manufacturer surat",
    "metal pallet manufacturer",
    "industrial pallet manufacturer",
    "heavy duty steel pallet",
    "custom steel pallet",
    "steel pallet wholesale",
    // === PRODUCTS — WALKWAY & STRUCTURAL ===
    "walkway plank manufacturer surat",
    "roof walkway plank",
    "steel walkway plank",
    "catwalk plank manufacturer",
    "chequered plate supplier surat",
    "MS angle manufacturer surat",
    "MS channel manufacturer surat",
    "structural steel components surat",
    "steel structure fabrication surat",
    "conveyor stringer fabrication",
    "material handling fabrication",
    // === INDUSTRIES SERVED ===
    "CNC bending for chemical industry",
    "press brake bending for pharma",
    "plate bending for pharmaceutical plant",
    "automotive plate bending",
    "automotive sheet metal fabrication",
    "construction steel fabrication",
    "plate bending for construction",
    "sheet metal for power plant",
    "sheet metal for solar energy",
    "solar mounting frame fabrication",
    "plate bending for sugar industry",
    "plate bending for textile industry",
    "plate bending for mining",
    "sheet metal for warehouse",
    "sheet metal for industrial shed",
    "sheet metal for HVAC",
    "plate bending for pressure vessels",
    "plate bending for boilers",
    "plate bending for tanks",
    // === WELDING SERVICES ===
    "MIG welding fabrication",
    "MIG welding surat",
    "TIG welding fabrication",
    "TIG welding surat",
    "arc welding fabrication",
    "welding fabrication surat",
    "structural welding surat",
    "heavy welding fabrication",
    "steel welding fabrication",
    // === BUYER INTENT — PRICE & QUOTE ===
    "CNC plate bending price india",
    "press brake bending price india",
    "sheet metal fabrication price india",
    "laser cutting price india",
    "plate bending price india",
    "sheet metal fabrication cost india",
    "get a quote plate bending",
    "free quote CNC bending",
    "plate bending estimate",
    "plate bending rate per kg",
    "sheet metal bending rate per kg",
    "laser cutting rate per kg",
    "CNC plate bending price surat",
    "press brake bending price surat",
    "CNC bending cost surat",
    "bulk fabrication price",
    "contract fabrication price",
    // === BUYER INTENT — SUPPLIER / MANUFACTURER ===
    "CNC plate bending manufacturer india",
    "plate bending supplier india",
    "press brake bending manufacturer india",
    "steel fabricator india",
    "sheet metal company india",
    "best CNC bending company india",
    "top press brake service surat",
    "reliable plate bending supplier india",
    "trusted CNC fabricator india",
    "plate bending fabrication export",
    "export plate bent parts",
    "steel fabricated components export india",
    "plate bending supplier surat",
    "steel fabricator surat",
    // === BUYER INTENT — JOB WORK & B2B ===
    "plate bending job work",
    "plate bending job work surat",
    "plate bending job work india",
    "CNC bending job work surat",
    "CNC bending job work india",
    "press brake job work surat",
    "sheet metal job work surat",
    "sheet metal job work india",
    "laser cutting job work surat",
    "CNC job work surat",
    "CNC job work gujarat",
    "job work fabrication india",
    "contract CNC bending manufacturing",
    "contract fabrication steel india",
    "outsource plate bending india",
    "outsource CNC bending india",
    "B2B plate bending india",
    "B2B CNC bending india",
    "bulk order plate bending",
    "bulk order CNC bending",
    "wholesale plate bending",
    "prototype plate bending india",
    "DXF file CNC bending",
    "DWG file CNC bending",
    "CAD drawing plate bending",
    // === LOCATION — SURAT ===
    "sheet metal fabrication surat",
    "steel fabrication surat",
    "laser cutting surat",
    "plasma cutting surat",
    "plate bending surat",
    "press brake surat",
    "CNC bending surat",
    "sheet metal works surat",
    "fabrication company surat",
    "metal works surat",
    "sheet metal fabrication kamrej",
    "steel fabrication kamrej",
    // === LOCATION — GUJARAT ===
    "sheet metal fabrication gujarat",
    "steel fabrication gujarat",
    "laser cutting gujarat",
    "CNC plate bending gujarat",
    "CNC bending gujarat",
    "press brake bending gujarat",
    "plate bending gujarat",
    "plate bending bharuch",
    "CNC bending bharuch",
    "plate bending ankleshwar",
    "CNC bending ankleshwar",
    "plate bending vadodara",
    "CNC bending vadodara",
    "sheet metal fabrication ahmedabad",
    "press brake bending ahmedabad",
    "laser cutting ahmedabad",
    "sheet metal fabrication vapi",
    "laser cutting vapi",
    "sheet metal fabrication rajkot",
    "laser cutting gujarat",
    // === LOCATION — MAHARASHTRA ===
    "sheet metal fabrication maharashtra",
    "sheet metal fabrication mumbai",
    "laser cutting mumbai",
    "steel fabrication mumbai",
    "plate bending mumbai",
    "sheet metal fabrication pune",
    "plate bending pune",
    "sheet metal fabrication nashik",
    "sheet metal fabrication thane",
    // === LOCATION — INDIA ===
    "sheet metal fabrication india",
    "steel fabrication india",
    "laser cutting india",
    "plate bending india",
    "CNC bending india",
    "press brake india",
    "sheet metal supplier india",
    "sheet metal manufacturer india",
    "pan india steel fabrication",
    "nationwide plate bending supplier",
    "all india CNC bending supplier",
    "heavy fabrication company india",
    // === WORLDWIDE / EXPORT ===
    "CNC plate bending export india",
    "press brake bent parts export",
    "laser cut parts export india",
    "custom CNC bending export",
    "B2B plate bending worldwide",
    "plate bending supplier worldwide",
    "steel fabrication for export",
    "industrial fabrication export india",
    "precision CNC bent parts worldwide",
    "custom plate bent parts global",
    "steel component manufacturer india export",
    // === LONG-TAIL SEARCH PHRASES ===
    "CNC plate bending service near me",
    "press brake bending service near me",
    "best CNC press brake company surat",
    "CNC plate bending company in gujarat",
    "industrial plate bending company surat india",
    "MS base plate manufacturer in surat gujarat",
    "foundation bolt manufacturer in surat india",
    "custom CNC bending fabrication india",
    "B2B plate bending parts supplier india",
    "CNC bent sheet metal parts india",
    "plate bending job work company surat",
    "CNC bending and cutting service surat",
    "plate rolling and bending service surat",
    "structural steel fabrication company surat",
    "heavy fabrication company surat gujarat",
    "industrial CNC bending manufacturer surat",
    "steel components manufacturer surat gujarat",
    "quick turnaround CNC bending surat",
    "urgent plate bending job work surat",
    "plate bending for construction projects",
    "steel base plates for towers and structures",
    "anchor bolts for buildings india",
    "purlins for warehouse roofing india",
    "steel pallets for warehouse storage",
    "industrial steel components manufacturer india",
    "custom metal parts CNC bending india",
    "CNC press brake bending for OEM manufacturers",
    "plate bending for industrial tanks",
    "plate bending for pressure vessel fabrication",
    "get quote CNC plate bending india",
    "bulk CNC bending order india",
    "contract CNC bending manufacturer surat",
    "precision plate bending service surat india",
  ],
  address: {
    streetAddress:
      "Kamrej, Surat, Gujarat",
    locality: "Surat",
    region: "Gujarat",
    postalCode: "394185",
    country: "IN",
  },
  mapUrl:
    "https://maps.google.com/?q=Balaji+Engineering+Works+Plot+No.+11+12+Soham+Industrial+Estate+NH+8+Kamrej+Surat+Gujarat+394185",
} as const;
